version: '4'

include:
  # You could get this from a submodule in a real repo.
  - ../docker-compose.yml

services:
  # The subgraph cli as a box that we can mount our code into as a volume.
  subgraph-cli:
    image: rainprotocol/subgraph.subgraph-cli
    profiles: ["subgraph-cli"]
    volumes:
      - ./:/subgraph
    working_dir: /subgraph
