name: Build docker

on: [push]

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ethnode
        run: |
          docker build -t ethnode ./ethnode
