name: Build docker

on: [push]

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build evm-node
        run: |
          docker build -t rainprotocol/subgraph.evm-node ./evm-node
          docker push rainprotocol/subgraph.evm-node

      - name: Build subgraph-cli
        run: |
          docker build -t rainprotocol/subgraph.subgraph-cli ./subgraph-cli
          docker push rainprotocol/subgraph.subgraph-cli