name: Build docker

on: [push]

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ethnode
        run: |
          docker build -t subgraph.ethnode ./ethnode
          docker push subgraph.ethnode

      - name: Build subgraph-cli
        run: |
          docker build -t subgraph.subgraph-cli ./subgraph-cli
          docker push subgraph.subgraph-cli