name: Build docker

on: [push]

env:
  CHANNEL: ${{ inputs.tag || github.head_ref || github.ref_name }}

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ethnode
        run: |
          docker build -t rainprotocol/subgraph.ethnode ./ethnode
          docker push rainprotocol/subgraph.ethnode

      - name: Build subgraph-cli
        run: |
          docker build -t rainprotocol/subgraph.subgraph-cli ./subgraph-cli
          docker push rainprotocol/subgraph.subgraph-cli

      - name: Build matchstick
        run: |
          docker build -t rainprotocol/matchstick ./matchstick
          docker push rainprotocol/matchstick