name: Build docker

on: [push]

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ethnode
        run: |
          docker build -t subgraph.ethnode ./ethnode
          docker push -t subgraph.ethnode

      - name: Build subgraph-cli
        run: |
          docker build -t subgraph.subgraph-cli ./subgraph-cli
          docker push -t subgraph.subgraph-cli