name: Test example subgraph

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-example-subgraph:
    name: Test example subgraph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        working-directory: example

      - name: Docker compose version
        run: |
          docker compose version
          docker --version
        working-directory: example

      - name: Docker compose up
        run: docker compose up -d
        working-directory: example

      - name: npm install for the graph cli service
        run: docker compose run -w /repo/subgraph subgraph-cli npm install
        working-directory: example

      - name: Codegen from subgraph
        run: docker compose run -w /repo/subgraph subgraph-cli graph codegen
        working-directory: example

      - name: Build the subgraph
        run: docker compose run -w /repo/subgraph subgraph-cli graph build
        working-directory: example

      - name: Deploy the subgraph
        run: |
          sleep 30
          docker ps
          docker logs example-graph-node-1
          docker compose exec example-graph-node-1 echo "$environment"
          docker compose run -w /repo/subgraph subgraph-cli graph deploy --node http://localhost:8020 -l "v0.0.0" example/test
          docker logs example-graph-node-1
        working-directory: example

      - name: Docker compose down
        run: docker compose down
        working-directory: example
