name: Test example subgraph

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-example-subgraph:
    name: Test example subgraph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        working-directory: example

      - name: Docker compose version
        run: |
          docker compose version
          docker --version
        working-directory: example

      - name: Docker compose up
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
        working-directory: example

      - name: npm install for the graph cli service
        run: docker compose run -w /repo/subgraph subgraph-cli npm install
        working-directory: example

      - name: Codegen from subgraph
        run: docker compose run -w /repo/subgraph subgraph-cli graph codegen
        working-directory: example

      - name: Build the subgraph
        run: docker compose run -w /repo/subgraph subgraph-cli graph build
        working-directory: example

      - name: Deploy the subgraph
        run: |
          set -x
          sleep 30
          docker ps
          docker logs example-graph-node-1
          docker logs ethnode
          docker compose -f docker-compose.yml -f docker-compose.ci.yml config
          docker compose run -w /repo/subgraph subgraph-cli graph deploy --node http://graph-node:8020 -l "v0.0.0" example/test
          docker logs example-graph-node-1
        working-directory: example

      - name: Docker compose down
        run: docker compose down
        working-directory: example
