name: Test example subgraph

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-example-subgraph:
    name: Test example subgraph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix run .#rainix-prelude
        working-directory: example

      - name: Docker compose up
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
        working-directory: example

      - name: npm install for the graph cli service
        run: docker compose run -w /repo/subgraph subgraph-cli npm install
        working-directory: example

      - name: Codegen from subgraph
        run: docker compose run -w /repo/subgraph subgraph-cli graph codegen
        working-directory: example

      - name: Build the subgraph
        run: docker compose run -w /repo/subgraph subgraph-cli graph build
        working-directory: example

      - name: Deploy the subgraph
        run: |
          docker compose run -w /repo/subgraph subgraph-cli graph create --node http://graph-node:8020 example/test
          docker compose run -w /repo/subgraph subgraph-cli graph deploy --node http://graph-node:8020 --ipfs http://ipfs:5001 -l "v0.0.0" example/test
        working-directory: example

      - name: Deploy contracts to ethnode
        run: nix run .#rainix-sol-artifacts

      - name: Docker compose down
        run: docker compose down
        working-directory: example
